### ISSUE TITLE
Faction Presence inconsistency

### ISSUE THREAD

**Issue by EricJFisher** [Elite-Kode/elitebgs#195] opened 2021-01-11 02:40 UTC
On the rare occasion (such as the example provided below of Riedquat on January 10th/11th) a faction will show up in EliteBGS as having an influence of NaN.

![riedquat](https://user-images.githubusercontent.com/5638847/104142814-21596b80-538b-11eb-8c5a-bf98903e31c5.PNG)

This also manifests itself in EliteBGS's API (specifically on getting a System's information with `factionDetails=true`. note: this is the v5 version of the API)

The way this manifests itself is instead of `faction_presence` coming through as an object, it comes through as an array. (the array from what I've seen typically just contains the one object, it just seems to wrap it in an array for some reason)

**Comment by SayakMukhopadhyay** [comment] 2021-04-27 11:39
Found the root cause of the issue. It happens when a faction has expanded into a system and the happiness value in empty. This causes an inconsistency in the db resulting in this. This issue has been fixed by ce31081b05e2b70ecf97dfc73ed6ba062fcde3eb which allows empty happiness values.

**Closed by SayakMukhopadhyay** 2021-04-27 11:39 UTC
